#!/usr/bin/env python3
"""Summarize hydrostatic-corrected corner endpoint pressures from case-analysis CSVs.

This helper does not reconstruct raw OpenFOAM fields. It reuses existing
`feature_minor_loss_timeseries.csv` products generated by the case-analysis
pipeline. Those CSVs already carry per-retained-time area-averaged endpoint
pressures on each named corner feature:

- `start_p_rgh_pa`
- `end_p_rgh_pa`
- `delta_p_rgh_pa = end_p_rgh_pa - start_p_rgh_pa`

The summary emitted here is therefore a windowed average over already
hydrostatic-corrected endpoint pressures.

Math used in the summary:

For one retained time `t` and one corner feature `f`:

- `p_before_rgh(t) = start_p_rgh_pa`
- `p_after_rgh(t) = end_p_rgh_pa`
- `delta_rgh(t) = p_after_rgh(t) - p_before_rgh(t)`
- `drop_start_to_end_rgh(t) = p_before_rgh(t) - p_after_rgh(t) = -delta_rgh(t)`

For the last `N` available retained times for that case:

- `mean_p_before_rgh = average(p_before_rgh(t))`
- `mean_p_after_rgh = average(p_after_rgh(t))`
- `mean_delta_rgh = average(delta_rgh(t))`
- `mean_drop_start_to_end_rgh = average(drop_start_to_end_rgh(t))`

The script reports both `mean_delta_rgh` and
`mean_drop_start_to_end_rgh` explicitly so the sign convention is visible
instead of implicit.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.case_analysis_profiles import get_case_analysis_profile  # noqa: E402


DEFAULT_SEARCH_ROOTS = [
    ROOT / "tmp" / "2026-06-18_overnight_analysis_queue" / "case_analysis",
]
DEFAULT_OUTPUT_DIR = ROOT / "work_products" / "2026-06-25_ethan_corner_pressure_drop_summary"
FEATURE_FILENAME = "feature_minor_loss_timeseries.csv"


@dataclass(frozen=True)
class PackageCandidate:
    source_id: str
    package_dir: Path
    feature_csv: Path
    available_times: tuple[float, ...]
    mtime_epoch_s: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--search-root",
        action="append",
        default=[],
        help=(
            "Directory to scan recursively for case-analysis package roots that contain "
            "`feature_minor_loss_timeseries.csv`. May be repeated."
        ),
    )
    parser.add_argument(
        "--package-root",
        action="append",
        default=[],
        help=(
            "Explicit case-analysis package root. The helper expects "
            "`<package-root>/feature_minor_loss_timeseries.csv`."
        ),
    )
    parser.add_argument(
        "--source-id",
        action="append",
        default=[],
        help="Optional source_id filter. May be repeated.",
    )
    parser.add_argument(
        "--window-size",
        action="append",
        type=int,
        default=[],
        help="Retained-time window size to average. May be repeated. Defaults to 5, 10, and 20.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help=f"Output directory. Default: {DEFAULT_OUTPUT_DIR}",
    )
    return parser.parse_args()


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, payload: dict[str, Any]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")


def iso_timestamp() -> str:
    from datetime import datetime

    return datetime.now().astimezone().isoformat(timespec="seconds")


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def load_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def finite_float(value: Any) -> float:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return math.nan
    return parsed


def truthy_flag(value: Any) -> int:
    token = str(value).strip().lower()
    return int(token in {"1", "true", "yes", "y"})


def discover_feature_csvs(search_roots: list[Path]) -> list[Path]:
    discovered: list[Path] = []
    for search_root in search_roots:
        if not search_root.exists():
            continue
        for feature_csv in search_root.rglob(FEATURE_FILENAME):
            if "raw_extraction" in feature_csv.parts:
                continue
            discovered.append(feature_csv)
    return sorted(set(discovered))


def build_candidate(feature_csv: Path) -> PackageCandidate | None:
    rows = load_csv_rows(feature_csv)
    if not rows:
        return None
    source_id = str(rows[0].get("source_id", "")).strip()
    if not source_id:
        return None
    available_times = sorted(
        {
            finite_float(row.get("time_s"))
            for row in rows
            if math.isfinite(finite_float(row.get("time_s")))
        }
    )
    return PackageCandidate(
        source_id=source_id,
        package_dir=feature_csv.parent,
        feature_csv=feature_csv,
        available_times=tuple(available_times),
        mtime_epoch_s=feature_csv.stat().st_mtime,
    )


def choose_best_candidates(
    candidates: list[PackageCandidate],
    source_filter: set[str],
) -> list[PackageCandidate]:
    grouped: dict[str, list[PackageCandidate]] = {}
    for candidate in candidates:
        if source_filter and candidate.source_id not in source_filter:
            continue
        grouped.setdefault(candidate.source_id, []).append(candidate)

    selected: list[PackageCandidate] = []
    for source_id in sorted(grouped):
        options = grouped[source_id]
        selected.append(
            max(
                options,
                key=lambda item: (
                    len(item.available_times),
                    item.available_times[-1] if item.available_times else -math.inf,
                    item.mtime_epoch_s,
                    str(item.package_dir),
                ),
            )
        )
    return selected


def corner_feature_order(source_id: str, rows: list[dict[str, str]]) -> list[str]:
    try:
        profile = get_case_analysis_profile(source_id)
    except KeyError:
        ordered = []
        seen: set[str] = set()
        for row in rows:
            if str(row.get("feature_kind", "")).strip() != "corner":
                continue
            feature_name = str(row["feature_name"])
            if feature_name not in seen:
                seen.add(feature_name)
                ordered.append(feature_name)
        return ordered
    return [
        feature_name
        for feature_name, definition in profile.feature_budgets.items()
        if definition.get("kind") == "corner"
    ]


def adjacent_major_spans(source_id: str, feature_name: str) -> str:
    try:
        profile = get_case_analysis_profile(source_id)
    except KeyError:
        return ""
    definition = profile.feature_budgets.get(feature_name, {})
    spans = definition.get("adjacent_major_spans", [])
    return "|".join(str(value) for value in spans)


def safe_mean(values: list[float]) -> float:
    finite_values = [value for value in values if math.isfinite(value)]
    if not finite_values:
        return math.nan
    return float(sum(finite_values) / len(finite_values))


def safe_stdev(values: list[float]) -> float:
    finite_values = [value for value in values if math.isfinite(value)]
    if len(finite_values) < 2:
        return math.nan
    return float(statistics.pstdev(finite_values))


def summarize_candidate(candidate: PackageCandidate, window_sizes: list[int]) -> list[dict[str, Any]]:
    rows = load_csv_rows(candidate.feature_csv)
    feature_order = corner_feature_order(candidate.source_id, rows)
    rows_by_feature: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        feature_name = str(row.get("feature_name", ""))
        if feature_name in feature_order:
            rows_by_feature.setdefault(feature_name, []).append(row)

    summary_rows: list[dict[str, Any]] = []
    unique_times = sorted(candidate.available_times)
    for window_size in window_sizes:
        selected_times = set(unique_times[-min(window_size, len(unique_times)) :])
        for feature_name in feature_order:
            feature_rows = [
                row
                for row in rows_by_feature.get(feature_name, [])
                if finite_float(row.get("time_s")) in selected_times
            ]
            feature_rows.sort(key=lambda row: finite_float(row.get("time_s")))
            if not feature_rows:
                continue

            start_patch = str(feature_rows[0].get("start_patch", ""))
            end_patch = str(feature_rows[0].get("end_patch", ""))
            time_values = [finite_float(row.get("time_s")) for row in feature_rows]
            start_prgh = [finite_float(row.get("start_p_rgh_pa")) for row in feature_rows]
            end_prgh = [finite_float(row.get("end_p_rgh_pa")) for row in feature_rows]
            delta_prgh = [finite_float(row.get("delta_p_rgh_pa")) for row in feature_rows]
            abs_delta_prgh = [finite_float(row.get("abs_delta_p_rgh_pa")) for row in feature_rows]
            drop_start_to_end = [
                -value if math.isfinite(value) else math.nan for value in delta_prgh
            ]
            start_p = [finite_float(row.get("start_p_pa")) for row in feature_rows]
            end_p = [finite_float(row.get("end_p_pa")) for row in feature_rows]
            delta_p = [finite_float(row.get("delta_p_pa")) for row in feature_rows]
            warning_values = [truthy_flag(row.get("warning_flag")) for row in feature_rows]

            summary_rows.append(
                {
                    "source_id": candidate.source_id,
                    "selected_package_dir": display_path(candidate.package_dir),
                    "feature_name": feature_name,
                    "adjacent_major_spans": adjacent_major_spans(candidate.source_id, feature_name),
                    "start_patch": start_patch,
                    "end_patch": end_patch,
                    "requested_window_count": window_size,
                    "available_time_count": len(unique_times),
                    "used_time_count": len(feature_rows),
                    "time_s_first_used": min(time_values),
                    "time_s_last_used": max(time_values),
                    "mean_start_p_rgh_pa": safe_mean(start_prgh),
                    "mean_end_p_rgh_pa": safe_mean(end_prgh),
                    "mean_delta_p_rgh_pa": safe_mean(delta_prgh),
                    "stdev_delta_p_rgh_pa": safe_stdev(delta_prgh),
                    "mean_pressure_drop_start_to_end_rgh_pa": safe_mean(drop_start_to_end),
                    "mean_abs_delta_p_rgh_pa": safe_mean(abs_delta_prgh),
                    "mean_start_p_pa": safe_mean(start_p),
                    "mean_end_p_pa": safe_mean(end_p),
                    "mean_delta_p_pa": safe_mean(delta_p),
                    "warning_row_count": sum(warning_values),
                    "warning_fraction": float(sum(warning_values) / len(warning_values)),
                    "math_note": (
                        "mean_delta_p_rgh_pa = average(end_p_rgh - start_p_rgh); "
                        "mean_pressure_drop_start_to_end_rgh_pa = average(start_p_rgh - end_p_rgh)"
                    ),
                }
            )
    return summary_rows


def build_selected_package_rows(candidates: list[PackageCandidate]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for candidate in candidates:
        rows.append(
            {
                "source_id": candidate.source_id,
                "package_dir": display_path(candidate.package_dir),
                "feature_csv": display_path(candidate.feature_csv),
                "available_time_count": len(candidate.available_times),
                "time_s_first_available": candidate.available_times[0] if candidate.available_times else math.nan,
                "time_s_last_available": candidate.available_times[-1] if candidate.available_times else math.nan,
            }
        )
    return rows


def write_readme(output_dir: Path, selected_rows: list[dict[str, Any]], summary_rows: list[dict[str, Any]], window_sizes: list[int]) -> None:
    source_ids = sorted({str(row["source_id"]) for row in selected_rows})
    feature_names = sorted({str(row["feature_name"]) for row in summary_rows})
    readme_path = output_dir / "README.md"
    lines = [
        "# Corner Pressure Drop Summary",
        "",
        f"Generated: `{iso_timestamp()}`",
        "",
        "## Purpose",
        "",
        "This package summarizes hydrostatic-corrected endpoint pressures across the",
        "named loop corners using existing `feature_minor_loss_timeseries.csv` case-analysis",
        "products.",
        "",
        "## Artifacts",
        "",
        "- `selected_case_packages.csv`: one chosen case-analysis package root per source_id",
        "- `corner_pressure_drop_window_summary.csv`: window-averaged corner endpoint pressures and deltas",
        "- `corner_pressure_drop_summary.json`: machine-readable run metadata",
        "",
        "## Scope",
        "",
        f"- selected source_ids: `{len(source_ids)}`",
        f"- corner features present: `{', '.join(feature_names)}`",
        f"- requested windows: `{', '.join(str(value) for value in window_sizes)}` retained times",
        "",
        "## Sign convention",
        "",
        "- `mean_delta_p_rgh_pa = average(end_p_rgh - start_p_rgh)`",
        "- `mean_pressure_drop_start_to_end_rgh_pa = average(start_p_rgh - end_p_rgh)`",
        "",
        "The second quantity is included so the start-to-end pressure-drop direction is",
        "explicit rather than inferred from a sign flip.",
    ]
    readme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    search_roots = [Path(path).resolve() for path in (args.search_root or [])]
    if not search_roots:
        search_roots = [path.resolve() for path in DEFAULT_SEARCH_ROOTS]
    explicit_package_roots = [Path(path).resolve() for path in (args.package_root or [])]
    window_sizes = sorted(set(args.window_size or [5, 10, 20]))
    if any(value <= 0 for value in window_sizes):
        raise ValueError(f"Every --window-size must be positive. Received: {window_sizes}")

    discovered_feature_csvs = discover_feature_csvs(search_roots)
    for package_root in explicit_package_roots:
        feature_csv = package_root / FEATURE_FILENAME
        if not feature_csv.exists():
            raise FileNotFoundError(f"Explicit package root is missing {FEATURE_FILENAME}: {package_root}")
        discovered_feature_csvs.append(feature_csv)
    discovered_feature_csvs = sorted(set(discovered_feature_csvs))

    candidates = [candidate for candidate in (build_candidate(path) for path in discovered_feature_csvs) if candidate is not None]
    selected_candidates = choose_best_candidates(candidates, set(args.source_id or []))
    if not selected_candidates:
        raise RuntimeError(
            "No case-analysis packages with feature_minor_loss_timeseries.csv were found for the requested search roots "
            f"and source filters. search_roots={[str(path) for path in search_roots]}"
        )

    output_dir = ensure_dir(Path(args.output_dir))
    selected_rows = build_selected_package_rows(selected_candidates)
    summary_rows: list[dict[str, Any]] = []
    for candidate in selected_candidates:
        summary_rows.extend(summarize_candidate(candidate, window_sizes))

    selected_csv = output_dir / "selected_case_packages.csv"
    summary_csv = output_dir / "corner_pressure_drop_window_summary.csv"
    summary_json = output_dir / "corner_pressure_drop_summary.json"

    write_csv(selected_csv, list(selected_rows[0].keys()), selected_rows)
    write_csv(summary_csv, list(summary_rows[0].keys()), summary_rows)
    write_json(
        summary_json,
        {
            "generated_at": iso_timestamp(),
            "search_roots": [display_path(path) for path in search_roots],
            "explicit_package_roots": [
                display_path(path) for path in explicit_package_roots
            ],
            "requested_source_ids": list(args.source_id or []),
            "window_sizes": window_sizes,
            "discovered_feature_csv_count": len(discovered_feature_csvs),
            "selected_package_count": len(selected_candidates),
            "summary_row_count": len(summary_rows),
            "artifacts": {
                "selected_case_packages_csv": display_path(selected_csv),
                "corner_pressure_drop_window_summary_csv": display_path(summary_csv),
                "corner_pressure_drop_summary_json": display_path(summary_json),
            },
        },
    )
    write_readme(output_dir, selected_rows, summary_rows, window_sizes)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
